global:
  keycloak:
    externalHost: keycloak.mybank.test

  frontend:
    externalHost: frontend.mybank.test

  kibana:
    externalHost: kibana.mybank.test

  grafana:
    externalHost: grafana.mybank.test
