global:
  keycloak:
    externalHost: keycloak.mybank.local

  frontend:
    externalHost: frontend.mybank.local

  kibana:
    externalHost: kibana.mybank.local

  grafana:
    externalHost: grafana.mybank.local
