apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-accounts-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-accounts-db:5432/accounts_db"
  KEYCLOAK_JWK_SET_URI: "http://{{ .Release.Name }}-keycloak:8080/realms/mybank/protocol/openid-connect/certs"
  KEYCLOAK_TOKEN_URI: "http://{{ .Release.Name }}-keycloak:8080/realms/mybank/protocol/openid-connect/token"
  NOTIFICATIONS_URL: "http://{{ .Release.Name }}-notifications:8085"
