apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-accounts-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-accounts-db:5432/accounts_db"
  KEYCLOAK_JWK_SET_URI: "http://{{ .Release.Name }}-keycloak:8080/realms/mybank/protocol/openid-connect/certs"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Release.Name }}-kafka:9092"
  ZIPKIN_URL: "http://{{ .Release.Name }}-zipkin:9411"
  LOGSTASH_HOST: "{{ .Release.Name }}-logstash"
  LOGSTASH_PORT: "5000"
  SPRING_PROFILES_ACTIVE: "k8s"
