apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: "{{ .Values.global.accounts.image.repository }}:{{ .Values.global.accounts.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-accounts-config
            - secretRef:
                name: {{ .Release.Name }}-accounts-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 15
