apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
data:
  ACCOUNTS_URL: "http://{{ .Release.Name }}-gateway"
  CASH_URL: "http://{{ .Release.Name }}-gateway"
  TRANSFER_URL: "http://{{ .Release.Name }}-gateway"
  KEYCLOAK_AUTHORIZATION_URI: "http://{{ .Values.global.keycloak.externalHost }}/realms/mybank/protocol/openid-connect/auth"
  KEYCLOAK_TOKEN_URI: "http://{{ .Release.Name }}-keycloak:8080/realms/mybank/protocol/openid-connect/token"
  KEYCLOAK_JWK_SET_URI: "http://{{ .Release.Name }}-keycloak:8080/realms/mybank/protocol/openid-connect/certs"
  KEYCLOAK_USER_INFO_URI: "http://{{ .Release.Name }}-keycloak:8080/realms/mybank/protocol/openid-connect/userinfo"
  OAUTH2_REDIRECT_URI: "http://{{ .Values.global.frontend.externalHost }}/login/oauth2/code/{registrationId}"
  ZIPKIN_URL: "http://{{ .Release.Name }}-zipkin:9411"
  LOGSTASH_HOST: "{{ .Release.Name }}-logstash"
  LOGSTASH_PORT: "5000"
  SPRING_PROFILES_ACTIVE: "k8s"
