apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ "not-used" | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ "not-used" | b64enc }}
  FRONTEND_CLIENT_SECRET: {{ .Values.global.frontend.clientSecret | default "frontend-secret" | b64enc }}
