apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-transfer-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.global.postgres.username | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.global.postgres.password | b64enc }}
  TRANSFER_SERVICE_CLIENT_SECRET: {{ .Values.global.transfer.clientSecret | default "transfer-service-secret" | b64enc }}
