apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-secret
type: Opaque
data:
  admin-username: {{ .Values.global.keycloak.adminUsername | b64enc }}
  admin-password: {{ .Values.global.keycloak.adminPassword | b64enc }}
