spring:
  application:
    name: accounts
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/mybank/protocol/openid-connect/certs}
      client:
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8080/realms/mybank/protocol/openid-connect/token}
        registration:
          accounts-service:
            provider: keycloak
            client-id: accounts-service
            client-secret: ${ACCOUNTS_SERVICE_CLIENT_SECRET:accounts-service-secret}
            authorization-grant-type: client_credentials
            scope: openid
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/accounts_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

notifications:
  url: ${NOTIFICATIONS_URL:http://localhost:8085}

management:
  endpoints:
    web:
      exposure:
        include: health
