apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cash
  labels:
    app: cash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cash
  template:
    metadata:
      labels:
        app: cash
    spec:
      containers:
        - name: cash
          image: "{{ .Values.global.cash.image.repository }}:{{ .Values.global.cash.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-cash-config
            - secretRef:
                name: {{ .Release.Name }}-cash-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 15
