apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cash-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.global.postgres.username | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.global.postgres.password | b64enc }}
  CASH_SERVICE_CLIENT_SECRET: {{ .Values.global.cash.clientSecret | default "cash-service-secret" | b64enc }}
