apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-transfer-db
spec:
  podSelector:
    matchLabels:
      app: transfer-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: transfer
      ports:
        - port: 5432
          protocol: TCP
