apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-transfer-db-secret
type: Opaque
data:
  username: {{ .Values.global.postgres.username | b64enc }}
  password: {{ .Values.global.postgres.password | b64enc }}
