apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-zipkin
spec:
  podSelector:
    matchLabels:
      app: zipkin
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: accounts
        - podSelector:
            matchLabels:
              app: cash
        - podSelector:
            matchLabels:
              app: transfer
        - podSelector:
            matchLabels:
              app: notifications
        - podSelector:
            matchLabels:
              app: frontend
      ports:
        - port: 9411
          protocol: TCP
