apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-notifications-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-notifications-db:5432/notifications_db"
  KEYCLOAK_JWK_SET_URI: "http://{{ .Release.Name }}-keycloak:8080/realms/mybank/protocol/openid-connect/certs"
