apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-notifications-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-notifications-db:5432/notifications_db"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Release.Name }}-kafka:9092"
