pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = credentials('docker-registry-url')
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Validate') {
            steps {
                sh './gradlew :transfer:compileJava'
            }
        }

        stage('Build') {
            steps {
                sh './gradlew :transfer:build -x test'
            }
        }

        stage('Test') {
            steps {
                sh './gradlew :transfer:test'
            }
            post {
                always {
                    junit 'transfer/build/test-results/test/*.xml'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                sh "docker build -t ${DOCKER_REGISTRY}/mybank/transfer:${IMAGE_TAG} ./transfer"
                sh "docker push ${DOCKER_REGISTRY}/mybank/transfer:${IMAGE_TAG}"
            }
        }

        stage('Deploy to Test') {
            steps {
                sh '''
                    helm dependency update helm/mybank
                    helm upgrade --install mybank helm/mybank \
                        -f helm/mybank/values-test.yaml \
                        --set global.transfer.image.repository=${DOCKER_REGISTRY}/mybank/transfer \
                        --set global.transfer.image.tag=${IMAGE_TAG} \
                        -n test --create-namespace
                '''
            }
        }

        stage('Helm Test') {
            steps {
                sh 'helm test mybank -n test --timeout 120s'
            }
        }

        stage('Approve Production') {
            steps {
                input message: 'Deploy to production?', ok: 'Deploy'
            }
        }

        stage('Deploy to Production') {
            steps {
                sh '''
                    helm upgrade --install mybank helm/mybank \
                        -f helm/mybank/values-prod.yaml \
                        --set global.transfer.image.repository=${DOCKER_REGISTRY}/mybank/transfer \
                        --set global.transfer.image.tag=${IMAGE_TAG} \
                        -n prod --create-namespace
                '''
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed!'
        }
        success {
            echo 'Pipeline completed successfully!'
        }
    }
}
